### ISSUE TITLE
Compilation failure: text blocks are not supported in -source 11

### ISSUE THREAD

**Issue by pzygielo** [Apress/definitive-guide-jakarta-ee-security#2]
https://github.com/Apress/definitive-guide-jakarta-ee-security/blob/3e4fa162d1edbb612213ad7079570eb4ce578e8f/chapter5-jakarta-security/5-form-mechanism-custom-store/src/main/java/org/omnifaces/definitivesecurity/chapter/security/simplemechanisminteract/LoginServlet.java#L21-L25

https://github.com/Apress/definitive-guide-jakarta-ee-security/blob/3e4fa162d1edbb612213ad7079570eb4ce578e8f/pom.xml#L77

**Comment by keilw** [comment]
source 11 was a mistake by @arjantijms for the umbrella POM, it should not apply here anymore.

**Comment by pzygielo** [comment]
Why would you close this issue while the setting is still in place then?
